mysql:
  host: 'localhost'
  user: 'LPAMB'
  password: 'LpamBroot'
  database: 'LPAMB_track_data'
  connectionLimit: 100,
  maxIdle: 50,
  waitForConnections: true,
  enableKeepAlive: true,
  keepAliveInitialDelay: 0,
  idleTimeout: 120000,
  port: 3306